---
- name: "This is to demonstrate Nested loops"
  hosts: all
  become: yes
  tasks:
    - name: Copy module with nested loop
      copy:
        src: "{{ item[0] }}"
        dest: "{{ item[1] }}"
      with_nested:
        - [ '/etc/passwd','/etc/group','/etc/fstab' ]
        - [ '/tmp', '/mnt', '/opt' ]