---
- name: "This is to demonstrate Nested loops"
  hosts: all
  become: yes
  vars:
    myfile:
      - /etc/passwd
      - /etc/group
      - /etc/fstab

    mydir:
      - /tmp
      - /mnt
      - /opt
      
  tasks:
    - name: Copy module with nested loop
      copy:
        src: "{{ item[0] }}"
        dest: "{{ item[1] }}"
      with_nested:
        - "{{ myfile }}"
        - "{{ mydir }}"