---
- name: Check Disk Space utilization
  hosts: web-server
  become: yes
  tasks:
    - name: Get disk usage
      command: df -h
      register: disk_usage
    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage
    - name: Send Slack alert if disk usage is high
      community.general.slack_webhook:
        url: https://hooks.slack.com/services/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
        msg: 🚨 *Warning:* Disk usage on `{{ inventory_hostname }}` is at *{{
          disk_usage.stdout }}%*!
      when: disk_usage.stdout|int > 50
