---
- name: Add groups to the system
  hosts: all
  become: yes
  vars:
    mygrps:
      - test
      - dev
      - prod
  tasks:
    - name: Creating Groups in the system
      group:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ mygrps }}"