---
- name: This is my firt playbook file to run the plays
  hosts: all
  become: yes
  tasks:
  - copy:
      src: /etc/passwd
      dest: /tmp
      owner: nani
      group: nanigrp
      mode: 0777

  - file:
      path: /tmp/aws
      state: directory

  - apt:
      name: tree
      update_cache: yes
      state: present