---
- name: Installing Package.
  hosts: all
  become: yes
  vars:
    Package_Name: "{{ Package_Name }}"
  tasks:
    - name: Installing {{ Package_Name }}
      apt:
        name: "{{ Package_Name }}"
        update_cache: yes
        state: present
