---
- name: Installing Java Package on Ubuntu 18.04
  hosts: all
  become: yes
  tasks:
    - name: Installing openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present