---
- name: Installing Apache2 and Starting Services and Placing a project in It
  hosts: all
  become: yes
  tasks:
    - name: Install Apache2 Package
      apt:
        name: apache2
        update_cache: yes
        state: present

    - name: Create a Directory for the source Code
      file: 
        path: /source
        state: directory
        mode: 0777
        owner: devops
        group: devops
    
    - name: Download Project from the Jfrog Artifactory
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page283/lodge.zip
        dest: /source
        mode: 0777
        owner: devops
        group: devops

    - name: UnZip the Source Code
      unarchive:
          src: /source/lodge.zip
          dest: /source/
          remote_src: yes

    - name: Remove unZipped Archive 
      command: sudo rm -rf /source/lodge.zip

    - name: Run Apache2 Service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy the source file to apache directory
      copy:
        src: /source/lodge-html/
        dest: /var/www/html
        remote_src: yes

    - name: Enable Port 8080 instead of 80 and Listen to 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080