---
- name: Check CPU and RAM utilization and trigger Email
  hosts: web-server
  become: yes
  vars_files:
    vars/smtp_secret.yml
  tasks:
  - name: Transfer executable shellscript
    copy:
      src: /home/devops/shellscripts/metrics.sh
      dest: /opt/metrics.sh
      mode: 0775
  
  - name: Execute shellscript
    ansible.builtin.shell: /opt/metrics.sh > /home/devops/shellscripts/metric-log.txt
    args:
      executable: /bin/bash
  
  - name: Trigger emails to Team
    mail:
      host: smtp.gmail.com
      port: 587
      subtype: html
      username: kadurunarendra@gmail.com
      from: kadurunarendra@gmail.com
      to: kadurunarendra@gmail.com
      attach: /home/devops/shellscripts/metric-log.txt
      subject: Ansible-report for monitoring CPU and Memory Usage
      body: 'Monitoring has been successfully provisioned.'
    delegate_to: localhost