---
- name: Check CPU and RAM utilization and trigger Email
  hosts: web-server
  become: yes
  vars_files:
    vars/smtp_secret.yml
  vars:
    email_smtp_server: 'smtp.gmail.com'
    email_smtp_server_port: '587'
    email_smtp_from_address: 'kadurunarendra@gmail.com'
    email_smtp_to_address:
          - 'Harish L <lharish609@gmail.com>'
    #email_smtp_cc_address:
    #      - 'John Doe <john@gmail.com>'
    email_smtp_replyto_address: 'no-reply@lab.local'
    email_report_body: "This is a demo email. Check demo attachment."
    email_smtp_subject: "Ansible Email Notification - Demo"
    report_file_name: /home/devops/shellscripts/metric-log.txt

  tasks:
  - name: Transfer executable shellscript
    copy:
      src: /home/devops/shellscripts/metrics.sh
      dest: /opt/metrics.sh
      mode: 0775
  
  - name: Execute shellscript
    ansible.builtin.shell: /opt/metrics.sh > /home/devops/shellscripts/metric-log.txt
    args:
      executable: /bin/bash
  
  - name: Email notification
    include_role:
      name: send-email