---
- name: Check CPU and RAM utilization and trigger Email
  hosts: web-server
  become: yes
  tasks:
  - name: Transfer executable shellscript
    copy:
      src: /home/devops/shellscripts/metrics.sh
      dest: /opt/metrics.sh
      mode: 0775
  
  - name: Execute shellscript
    ansible.builtin.shell: /opt/metrics.sh > /home/devops/shellscripts/metric-log.txt
    args:
      executable: /bin/bash
  
  - name: Store file into /tmp/fetched in the Server from Nodes
    ansible.builtin.fetch:
      src: /home/devops/shellscripts/metric-log.txt
      dest: /tmp/fetched

  - name: Create a zip archive of /path/to/foo
    archive:
      path: /tmp/fetched
      dest: /tmp/fetched.zip
      format: zip
  
  - name: Sending an e-mail using Gmail SMTP servers
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: kadurunarendra@gmail.com
      password: dbqgmrocmnosfwqo
      to: 
        - lharish609@gmail.com
        - harishlankepalli555@gmail.com
        - kadurunarendra@gmail.com
      subject: Ansible-report
      body: System has been successfully provisioned.
      attach: /home/devops/shellscripts/metric-log.txt
    delegate_to: {{ ansible-server }}
