---
- name: Stop all the apache Services Running
  hosts: all
  become: yes
  tasks:
    - name: Apache2 stop and disable
      service:
        name: apache2
        state: stopped
        enabled: no

    - name: Remove Apache2 Service
      apt:
        name: apache2
        state: absent

    - name: AutoRemove Apache2 Package
      command: sudo apt autoremove apache2 -y
    
    - name: Purge Apache2 Package
      command: sudo apt purge apache2 -y
