---
- name: Removing Java Package
  hosts: all
  become: yes
  tasks:
    - name: Removing openjdk-11-jdk on Debian Servers
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Removing java-11-openjdk on CentOs Servers
      yum:
        name: java-11-openjdk
        update_cache: yes
        state: absent
      when: ansible_facts['os_family'] == "RedHat"