---
- name: Stop all The apache Services Running
  hosts: all
  become: yes
  tasks:
    - name: Apache2 stop and disable
      service:
        name: apache2
        state: stopped
        enabled: no

    - name: Remove Apache2 Service
      apt:
        name: apache2
        state: absent