---
- name: This is my firt playbook file to run the plays
  hosts: web-server
  become: yes
  tasks:
    - import_tasks: task1.yaml   

- name: This is the second Task running on the app-server group
  hosts: app-server
  become: yes
  tasks:
    - import_tasks: task2.yaml 
    