---
- name: "This is to demonstrate Hash loops"
  hosts: all
  become: yes
  tasks:
    - name: Copy module with Hash loop
      copy:
        src: "{{ item.a }}"
        dest: "{{ item.b }}"
      with_items:
        - { a: '/etc/passwd', b: '/tmp' }
        - { a: '/etc/group', b: '/mnt' }
        - { a: '/etc/fstab', b: '/opt' }