- name: Add Jenkins GPG key to keyring
  shell: "{{ jenkins_gpg_key }}"
  ignore_errors: true
  changed_when: false
- name: Add Jenkins repository to sources.list
  shell: "{{ jenkins_repo }}"
- name: Update APT cache
  apt:
    update_cache: yes
- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  notify:
  - Start Jenkins Service
- name: Wait for Jenkins to start up
  wait_for: timeout=20
- name: Get Jenkins password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result
- name: Password to "Unlock Jenkins"
  debug:
    var: result.stdout
